//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="gramaticaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IgramaticaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] gramaticaParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] gramaticaParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDcl([NotNull] gramaticaParser.DclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDcl([NotNull] gramaticaParser.DclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDcl([NotNull] gramaticaParser.VarDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDcl([NotNull] gramaticaParser.VarDclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] gramaticaParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] gramaticaParser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FmtPrintStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFmtPrintStmt([NotNull] gramaticaParser.FmtPrintStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FmtPrintStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFmtPrintStmt([NotNull] gramaticaParser.FmtPrintStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] gramaticaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] gramaticaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] gramaticaParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] gramaticaParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] gramaticaParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] gramaticaParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpr([NotNull] gramaticaParser.LogicalOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpr([NotNull] gramaticaParser.LogicalOrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpr([NotNull] gramaticaParser.LogicalAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpr([NotNull] gramaticaParser.LogicalAndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] gramaticaParser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] gramaticaParser.EqualityExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpr([NotNull] gramaticaParser.RelationalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpr([NotNull] gramaticaParser.RelationalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpr([NotNull] gramaticaParser.AddExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpr([NotNull] gramaticaParser.AddExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulExpr([NotNull] gramaticaParser.MulExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulExpr([NotNull] gramaticaParser.MulExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] gramaticaParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] gramaticaParser.UnaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] gramaticaParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] gramaticaParser.PrimaryContext context);
}
