//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="gramaticaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IgramaticaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] gramaticaParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] gramaticaParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] gramaticaParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] gramaticaParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDecl([NotNull] gramaticaParser.FuncDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDecl([NotNull] gramaticaParser.FuncDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.paramsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamsList([NotNull] gramaticaParser.ParamsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.paramsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamsList([NotNull] gramaticaParser.ParamsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] gramaticaParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] gramaticaParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.structDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDecl([NotNull] gramaticaParser.StructDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.structDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDecl([NotNull] gramaticaParser.StructDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.fieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDecl([NotNull] gramaticaParser.FieldDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.fieldDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDecl([NotNull] gramaticaParser.FieldDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.structLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructLiteral([NotNull] gramaticaParser.StructLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.structLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructLiteral([NotNull] gramaticaParser.StructLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.fieldValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldValue([NotNull] gramaticaParser.FieldValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.fieldValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldValue([NotNull] gramaticaParser.FieldValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloque([NotNull] gramaticaParser.BloqueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloque([NotNull] gramaticaParser.BloqueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.breakStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStmt([NotNull] gramaticaParser.BreakStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.breakStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStmt([NotNull] gramaticaParser.BreakStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.continueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStmt([NotNull] gramaticaParser.ContinueStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.continueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStmt([NotNull] gramaticaParser.ContinueStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] gramaticaParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] gramaticaParser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.incDecStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncDecStmt([NotNull] gramaticaParser.IncDecStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.incDecStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncDecStmt([NotNull] gramaticaParser.IncDecStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.forStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmt([NotNull] gramaticaParser.ForStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.forStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmt([NotNull] gramaticaParser.ForStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.forWhileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForWhileStmt([NotNull] gramaticaParser.ForWhileStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.forWhileStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForWhileStmt([NotNull] gramaticaParser.ForWhileStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.forThreePartStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForThreePartStmt([NotNull] gramaticaParser.ForThreePartStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.forThreePartStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForThreePartStmt([NotNull] gramaticaParser.ForThreePartStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForInit([NotNull] gramaticaParser.ForInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForInit([NotNull] gramaticaParser.ForInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.forPost"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForPost([NotNull] gramaticaParser.ForPostContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.forPost"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForPost([NotNull] gramaticaParser.ForPostContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.switchStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStmt([NotNull] gramaticaParser.SwitchStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.switchStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStmt([NotNull] gramaticaParser.SwitchStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.caseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseStmt([NotNull] gramaticaParser.CaseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.caseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseStmt([NotNull] gramaticaParser.CaseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.defaultStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultStmt([NotNull] gramaticaParser.DefaultStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.defaultStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultStmt([NotNull] gramaticaParser.DefaultStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] gramaticaParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] gramaticaParser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.elseIfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfStmt([NotNull] gramaticaParser.ElseIfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.elseIfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfStmt([NotNull] gramaticaParser.ElseIfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.elseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStmt([NotNull] gramaticaParser.ElseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.elseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStmt([NotNull] gramaticaParser.ElseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaracion([NotNull] gramaticaParser.DeclaracionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.declaracion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaracion([NotNull] gramaticaParser.DeclaracionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.assignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignacion([NotNull] gramaticaParser.AssignacionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.assignacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignacion([NotNull] gramaticaParser.AssignacionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] gramaticaParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] gramaticaParser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.printStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStmt([NotNull] gramaticaParser.PrintStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.printStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStmt([NotNull] gramaticaParser.PrintStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] gramaticaParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] gramaticaParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpresion([NotNull] gramaticaParser.ExpresionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.expresion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpresion([NotNull] gramaticaParser.ExpresionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpr([NotNull] gramaticaParser.LogicalOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.logicalOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpr([NotNull] gramaticaParser.LogicalOrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpr([NotNull] gramaticaParser.LogicalAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.logicalAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpr([NotNull] gramaticaParser.LogicalAndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] gramaticaParser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.equalityExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] gramaticaParser.EqualityExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpr([NotNull] gramaticaParser.RelationalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.relationalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpr([NotNull] gramaticaParser.RelationalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpr([NotNull] gramaticaParser.AddExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpr([NotNull] gramaticaParser.AddExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulExpr([NotNull] gramaticaParser.MulExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.mulExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulExpr([NotNull] gramaticaParser.MulExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] gramaticaParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] gramaticaParser.UnaryExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sliceFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceFunc([NotNull] gramaticaParser.SliceFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sliceFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceFunc([NotNull] gramaticaParser.SliceFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sliceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceType([NotNull] gramaticaParser.SliceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sliceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceType([NotNull] gramaticaParser.SliceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.typeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpec([NotNull] gramaticaParser.TypeSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.typeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpec([NotNull] gramaticaParser.TypeSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.sliceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSliceLiteral([NotNull] gramaticaParser.SliceLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.sliceLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSliceLiteral([NotNull] gramaticaParser.SliceLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] gramaticaParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] gramaticaParser.PrimaryContext context);
}
