//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from gramatica.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IgramaticaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class gramaticaBaseListener : IgramaticaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] gramaticaParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] gramaticaParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDcl([NotNull] gramaticaParser.DclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDcl([NotNull] gramaticaParser.DclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDcl([NotNull] gramaticaParser.VarDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDcl([NotNull] gramaticaParser.VarDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStmt([NotNull] gramaticaParser.ExprStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStmt([NotNull] gramaticaParser.ExprStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FmtPrintStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFmtPrintStmt([NotNull] gramaticaParser.FmtPrintStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FmtPrintStmt</c>
	/// labeled alternative in <see cref="gramaticaParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFmtPrintStmt([NotNull] gramaticaParser.FmtPrintStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] gramaticaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] gramaticaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] gramaticaParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] gramaticaParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] gramaticaParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] gramaticaParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.logicalOrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOrExpr([NotNull] gramaticaParser.LogicalOrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.logicalOrExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOrExpr([NotNull] gramaticaParser.LogicalOrExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.logicalAndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndExpr([NotNull] gramaticaParser.LogicalAndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.logicalAndExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndExpr([NotNull] gramaticaParser.LogicalAndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpr([NotNull] gramaticaParser.EqualityExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.equalityExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpr([NotNull] gramaticaParser.EqualityExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpr([NotNull] gramaticaParser.RelationalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.relationalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpr([NotNull] gramaticaParser.RelationalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.addExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddExpr([NotNull] gramaticaParser.AddExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.addExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddExpr([NotNull] gramaticaParser.AddExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.mulExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulExpr([NotNull] gramaticaParser.MulExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.mulExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulExpr([NotNull] gramaticaParser.MulExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpr([NotNull] gramaticaParser.UnaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.unaryExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpr([NotNull] gramaticaParser.UnaryExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] gramaticaParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] gramaticaParser.PrimaryContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
